/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Panels.customerPanel;
import GUI.Panels.customerPlusPanel;
import GUI.Panels.jobPanel;
import GUI.Panels.jobPlusPanel;
import GUI.Panels.reportsPanel;
import GUI.Panels.stockPanel;

/**
 *
 * @author amenu
 */
public class FranchiseeForm extends javax.swing.JFrame {

    jobPlusPanel p1;
    customerPlusPanel p2;
    stockPanel p3;
    reportsPanel p4;

    /**
     * Creates new form Franchisee
     */
    public FranchiseeForm() {
        initComponents();
        p1 = new jobPlusPanel();
        p2 = new customerPlusPanel();
        p3 = new stockPanel();
        p4 = new reportsPanel();
        
        tabbedFranchiseePanel.addTab("Job", p1);
        tabbedFranchiseePanel.addTab("Customer", p2);
        tabbedFranchiseePanel.addTab("Stock", p3);
        tabbedFranchiseePanel.addTab("Reports", p4);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupJobTypeRadioButtons = new javax.swing.ButtonGroup();
        franchiseePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        tabbedFranchiseePanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        franchiseePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Franchisee Dashboard");

        tabbedFranchiseePanel.setFocusable(false);
        tabbedFranchiseePanel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout franchiseePanelLayout = new javax.swing.GroupLayout(franchiseePanel);
        franchiseePanel.setLayout(franchiseePanelLayout);
        franchiseePanelLayout.setHorizontalGroup(
            franchiseePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(franchiseePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(tabbedFranchiseePanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        franchiseePanelLayout.setVerticalGroup(
            franchiseePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(franchiseePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbedFranchiseePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(franchiseePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(franchiseePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FranchiseeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FranchiseeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FranchiseeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FranchiseeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FranchiseeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel franchiseePanel;
    private javax.swing.ButtonGroup groupJobTypeRadioButtons;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTabbedPane tabbedFranchiseePanel;
    // End of variables declaration//GEN-END:variables
}
