/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author amenu
 */
public class InvoiceForm extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceForm
     */
    public InvoiceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoicePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        scrollTableInvoice = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        lblLabour = new javax.swing.JLabel();
        lblHourRate = new javax.swing.JLabel();
        lblMutiplyLabour = new javax.swing.JLabel();
        lblHoursWorked = new javax.swing.JLabel();
        lblValueLabour = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblValueTotal = new javax.swing.JLabel();
        lblVat = new javax.swing.JLabel();
        lblVATValue = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        lblValueOfGrand = new javax.swing.JLabel();
        btnPrintInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoicePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Invoice");

        tblInvoice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Part No", "Unit Cost", "Qty", "Cost £"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInvoice.setGridColor(new java.awt.Color(255, 255, 255));
        tblInvoice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblInvoiceFocusGained(evt);
            }
        });
        tblInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInvoiceMouseClicked(evt);
            }
        });
        tblInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblInvoiceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblInvoiceKeyTyped(evt);
            }
        });
        scrollTableInvoice.setViewportView(tblInvoice);
        if (tblInvoice.getColumnModel().getColumnCount() > 0) {
            tblInvoice.getColumnModel().getColumn(2).setResizable(false);
            tblInvoice.getColumnModel().getColumn(3).setResizable(false);
        }

        lblLabour.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblLabour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLabour.setText("Labour");

        lblHourRate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblHourRate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHourRate.setText("Hourly Rate");

        lblMutiplyLabour.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMutiplyLabour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMutiplyLabour.setText("x");

        lblHoursWorked.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblHoursWorked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoursWorked.setText("Hours Worked");

        lblValueLabour.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblValueLabour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueLabour.setText("Value");

        lblTotal.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total:");

        lblValueTotal.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblValueTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueTotal.setText("Value");

        lblVat.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblVat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVat.setText("VAT: ");

        lblVATValue.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblVATValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVATValue.setText("Value");

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblGrandTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrandTotal.setText("Grand Total:");

        lblValueOfGrand.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblValueOfGrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueOfGrand.setText("Value");

        btnPrintInvoice.setText("Print Invoice");

        javax.swing.GroupLayout invoicePanelLayout = new javax.swing.GroupLayout(invoicePanel);
        invoicePanel.setLayout(invoicePanelLayout);
        invoicePanelLayout.setHorizontalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollTableInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(invoicePanelLayout.createSequentialGroup()
                                .addComponent(lblLabour, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(invoicePanelLayout.createSequentialGroup()
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120)
                                        .addComponent(lblValueTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(invoicePanelLayout.createSequentialGroup()
                                        .addComponent(lblVat, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120)
                                        .addComponent(lblVATValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(invoicePanelLayout.createSequentialGroup()
                                        .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120)
                                        .addComponent(lblValueOfGrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(invoicePanelLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(lblHourRate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMutiplyLabour)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblHoursWorked)
                                        .addGap(37, 37, 37)
                                        .addComponent(lblValueLabour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(btnPrintInvoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        invoicePanelLayout.setVerticalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTableInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabour)
                    .addComponent(lblHourRate)
                    .addComponent(lblMutiplyLabour)
                    .addComponent(lblHoursWorked)
                    .addComponent(lblValueLabour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblValueTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVat)
                    .addComponent(lblVATValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrandTotal)
                    .addComponent(lblValueOfGrand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(invoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblInvoiceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblInvoiceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblInvoiceFocusGained

    private void tblInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInvoiceMouseClicked
        // TODO add your handling code here:
        lblStaffId.setText(tblInvoice.getValueAt(tblInvoice.getSelectedRow(), 0).toString());
        txtFirstName.setText(tblInvoice.getValueAt(tblInvoice.getSelectedRow(), 1).toString());
        txtSurname.setText(tblInvoice.getValueAt(tblInvoice.getSelectedRow(), 2).toString());
        txtEmail.setText(tblInvoice.getValueAt(tblInvoice.getSelectedRow(), 3).toString());
        cbJobTitle.getModel().setSelectedItem(tblInvoice.getValueAt(tblInvoice.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tblInvoiceMouseClicked

    private void tblInvoiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblInvoiceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblInvoiceKeyPressed

    private void tblInvoiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblInvoiceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblInvoiceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintInvoice;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblHourRate;
    private javax.swing.JLabel lblHoursWorked;
    private javax.swing.JLabel lblLabour;
    private javax.swing.JLabel lblMutiplyLabour;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVATValue;
    private javax.swing.JLabel lblValueLabour;
    private javax.swing.JLabel lblValueOfGrand;
    private javax.swing.JLabel lblValueTotal;
    private javax.swing.JLabel lblVat;
    private javax.swing.JScrollPane scrollTableInvoice;
    private javax.swing.JTable tblInvoice;
    // End of variables declaration//GEN-END:variables
}
