/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author amenu
 */
public class MechanicForm extends javax.swing.JFrame {

    /**
     * Creates new form MechanicForm
     */
    public MechanicForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblCompanyLogo = new javax.swing.JLabel();
        lblYourJobs = new javax.swing.JLabel();
        scrollTableYourJob = new javax.swing.JScrollPane();
        tblYourJob = new javax.swing.JTable();
        lblPendingJobs = new javax.swing.JLabel();
        lblJobTitle = new javax.swing.JLabel();
        lblJobNo = new javax.swing.JLabel();
        txtJobNo = new javax.swing.JTextField();
        lblJobStatus = new javax.swing.JLabel();
        cdJobStatus = new javax.swing.JComboBox<>();
        lblDateBooked = new javax.swing.JLabel();
        txtDateBooked = new javax.swing.JTextField();
        lblJobDescription = new javax.swing.JLabel();
        scrollJobDescription = new javax.swing.JScrollPane();
        txtJobDescription = new javax.swing.JTextArea();
        lblMake = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblVehicleRegNo = new javax.swing.JLabel();
        txtVehicleRegNo = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblTelephoneNo = new javax.swing.JLabel();
        txtTelephoneNo = new javax.swing.JTextField();
        btnAlterJob = new javax.swing.JButton();
        scrollTablePendingJob = new javax.swing.JScrollPane();
        tblPendingJob = new javax.swing.JTable();
        btnRemoveStaff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Mechanic Dashboard");

        lblCompanyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/companyLogo.jpg"))); // NOI18N

        lblYourJobs.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblYourJobs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYourJobs.setText("Your Jobs");

        tblYourJob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblYourJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Job Number", "Description", "Status", "Mechanic", "Customer", "Start Date", "End Date", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblYourJob.setGridColor(new java.awt.Color(255, 255, 255));
        tblYourJob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblYourJobFocusGained(evt);
            }
        });
        tblYourJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblYourJobMouseClicked(evt);
            }
        });
        tblYourJob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblYourJobKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblYourJobKeyTyped(evt);
            }
        });
        scrollTableYourJob.setViewportView(tblYourJob);

        lblPendingJobs.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblPendingJobs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendingJobs.setText("Pending Jobs");

        lblJobTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblJobTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJobTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jobIcon.png"))); // NOI18N
        lblJobTitle.setText("Job Detail");

        lblJobNo.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblJobNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJobNo.setText("Job No:");

        txtJobNo.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblJobStatus.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblJobStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJobStatus.setText("Job Status:");

        cdJobStatus.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        cdJobStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Active", "Complete" }));

        lblDateBooked.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblDateBooked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateBooked.setText("Date Booked:");

        txtDateBooked.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblJobDescription.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblJobDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJobDescription.setText("Job Description:");

        txtJobDescription.setEditable(false);
        txtJobDescription.setColumns(20);
        txtJobDescription.setRows(5);
        scrollJobDescription.setViewportView(txtJobDescription);

        lblMake.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMake.setText("Make:");

        txtMake.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblModel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModel.setText("Model:");

        txtModel.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblVehicleRegNo.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblVehicleRegNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicleRegNo.setText("Vehicle Registration No:");

        txtVehicleRegNo.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblCustomerName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerName.setText("Customer Name:");

        txtCustomerName.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblTelephoneNo.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblTelephoneNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelephoneNo.setText("Telephone Number:");

        txtTelephoneNo.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        btnAlterJob.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterJob.setText("Alter Job");

        tblPendingJob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblPendingJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Job Number", "Description", "Status", "Mechanic", "Customer", "Start Date", "End Date", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPendingJob.setGridColor(new java.awt.Color(255, 255, 255));
        tblPendingJob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblPendingJobFocusGained(evt);
            }
        });
        tblPendingJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPendingJobMouseClicked(evt);
            }
        });
        tblPendingJob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblPendingJobKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblPendingJobKeyTyped(evt);
            }
        });
        scrollTablePendingJob.setViewportView(tblPendingJob);

        btnRemoveStaff.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoveStaff.setText("Pick Job");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblYourJobs)
                        .addGap(460, 460, 460)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblJobStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdJobStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblDateBooked)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDateBooked, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                            .addComponent(lblJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(scrollTablePendingJob, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblVehicleRegNo)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblCustomerName)
                                                    .addGap(57, 57, 57)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblTelephoneNo)
                                                .addGap(33, 33, 33)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtVehicleRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblMake)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblModel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblJobDescription)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scrollJobDescription))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoveStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scrollTableYourJob, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(lblJobNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPendingJobs))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAlterJob, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCompanyLogo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYourJobs)
                            .addComponent(lblJobTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblJobNo)
                                    .addComponent(txtJobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDateBooked)
                                        .addComponent(txtDateBooked, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblJobStatus)
                                        .addComponent(cdJobStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJobDescription)
                                    .addComponent(scrollJobDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(scrollTableYourJob, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(lblPendingJobs)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMake)
                                    .addComponent(lblModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtVehicleRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAlterJob, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblVehicleRegNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCustomerName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTelephoneNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRemoveStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(scrollTablePendingJob, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCompanyLogo)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblYourJobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblYourJobFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblYourJobFocusGained

    private void tblYourJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblYourJobMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblYourJobMouseClicked

    private void tblYourJobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblYourJobKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblYourJobKeyPressed

    private void tblYourJobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblYourJobKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblYourJobKeyTyped

    private void tblPendingJobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblPendingJobFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPendingJobFocusGained

    private void tblPendingJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendingJobMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPendingJobMouseClicked

    private void tblPendingJobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPendingJobKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPendingJobKeyPressed

    private void tblPendingJobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPendingJobKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPendingJobKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MechanicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MechanicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MechanicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MechanicForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MechanicForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterJob;
    private javax.swing.JButton btnRemoveStaff;
    private javax.swing.JComboBox<String> cdJobStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCompanyLogo;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDateBooked;
    private javax.swing.JLabel lblJobDescription;
    private javax.swing.JLabel lblJobNo;
    private javax.swing.JLabel lblJobStatus;
    private javax.swing.JLabel lblJobTitle;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPendingJobs;
    private javax.swing.JLabel lblTelephoneNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleRegNo;
    private javax.swing.JLabel lblYourJobs;
    private javax.swing.JScrollPane scrollJobDescription;
    private javax.swing.JScrollPane scrollTablePendingJob;
    private javax.swing.JScrollPane scrollTableYourJob;
    private javax.swing.JTable tblPendingJob;
    private javax.swing.JTable tblYourJob;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDateBooked;
    private javax.swing.JTextArea txtJobDescription;
    private javax.swing.JTextField txtJobNo;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtTelephoneNo;
    private javax.swing.JTextField txtVehicleRegNo;
    // End of variables declaration//GEN-END:variables
}
