/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

/**
 *
 * @author amenu
 */
public class reportsPanel extends javax.swing.JPanel {

    
    stockReportPanel p1;
    vehicleReportPanel p2;
    jobReportPanel p3;

    
    /**
     * Creates new form reportPanel
     */
    public reportsPanel() {
        initComponents();
                p1 = new stockReportPanel();
        p2 = new vehicleReportPanel();
        p3 = new jobReportPanel();
        
        
        tabbedReportPanel.addTab("Stock", p1);
        tabbedReportPanel.addTab("Vehicle", p2);
        tabbedReportPanel.addTab("Job", p3);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedReportPanel = new javax.swing.JTabbedPane();

        tabbedReportPanel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedReportPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedReportPanel)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReport3;
    private javax.swing.JButton btnGenerateReport4;
    private javax.swing.JButton btnPrintReport2;
    private javax.swing.JButton btnPrintReport3;
    private javax.swing.JComboBox<String> cbMechanicPicker;
    private javax.swing.JComboBox<String> cbMechanicPicker1;
    private javax.swing.JComboBox<String> cbMonthPicker3;
    private javax.swing.JComboBox<String> cbMonthPicker4;
    private javax.swing.JComboBox<String> cbYearPicker3;
    private javax.swing.JComboBox<String> cbYearPicker4;
    private javax.swing.JPanel jobReportPanel;
    private javax.swing.JPanel jobReportPanel1;
    private javax.swing.JLabel lblCompanyLogo10;
    private javax.swing.JLabel lblCompanyLogo8;
    private javax.swing.JLabel lblDate3;
    private javax.swing.JLabel lblDate4;
    private javax.swing.JLabel lblFilter2;
    private javax.swing.JLabel lblFilter3;
    private javax.swing.JLabel lblJobType;
    private javax.swing.JLabel lblJobType1;
    private javax.swing.JRadioButton rbAnnualService2;
    private javax.swing.JRadioButton rbAnnualService3;
    private javax.swing.JRadioButton rbMOT2;
    private javax.swing.JRadioButton rbMOT3;
    private javax.swing.JRadioButton rbMechanic;
    private javax.swing.JRadioButton rbMechanic2;
    private javax.swing.JRadioButton rbOverall2;
    private javax.swing.JRadioButton rbOverall3;
    private javax.swing.JRadioButton rbRepair2;
    private javax.swing.JRadioButton rbRepair3;
    private javax.swing.JScrollPane scrollTableJob;
    private javax.swing.JScrollPane scrollTableJob1;
    private javax.swing.JTabbedPane tabbedReportPanel;
    private javax.swing.JTable tblJob;
    private javax.swing.JTable tblJob1;
    // End of variables declaration//GEN-END:variables
}
