/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

/**
 *
 * @author amenu
 */
public class stockReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form stockReportPanel
     */
    public stockReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockLevelReportPanel = new javax.swing.JPanel();
        lblStockTitle = new javax.swing.JLabel();
        scrollTableStockReport = new javax.swing.JScrollPane();
        tblStockReport = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        cbMonthPicker = new javax.swing.JComboBox<>();
        cbYearPicker = new javax.swing.JComboBox<>();
        btnGenerateReport = new javax.swing.JButton();
        btnPrintReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        stockLevelReportPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblStockTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblStockTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockTitle.setText("Stock Report");

        tblStockReport.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblStockReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Part Name", "Code", "Manufacturer", "Vehicle Type", "Year(s)", "Price", "Initial Stock Level", "Initial Cost £", "Used", "Delivery", "New Stock Level", "Stock Cost £", "Low Level Threshold"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStockReport.setGridColor(new java.awt.Color(255, 255, 255));
        tblStockReport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblStockReportFocusGained(evt);
            }
        });
        tblStockReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockReportMouseClicked(evt);
            }
        });
        tblStockReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblStockReportKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblStockReportKeyTyped(evt);
            }
        });
        scrollTableStockReport.setViewportView(tblStockReport);

        lblDate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date");

        cbMonthPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));

        cbYearPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));

        btnGenerateReport.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerateReport.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.setBorder(null);
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        btnPrintReport.setBackground(new java.awt.Color(255, 255, 255));
        btnPrintReport.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnPrintReport.setText("Print Report");
        btnPrintReport.setBorder(null);
        btnPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stockLevelReportPanelLayout = new javax.swing.GroupLayout(stockLevelReportPanel);
        stockLevelReportPanel.setLayout(stockLevelReportPanelLayout);
        stockLevelReportPanelLayout.setHorizontalGroup(
            stockLevelReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockLevelReportPanelLayout.createSequentialGroup()
                .addGroup(stockLevelReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(stockLevelReportPanelLayout.createSequentialGroup()
                        .addGroup(stockLevelReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stockLevelReportPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblStockTitle))
                            .addGroup(stockLevelReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(stockLevelReportPanelLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(stockLevelReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDate)
                                        .addGroup(stockLevelReportPanelLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(cbMonthPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbYearPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stockLevelReportPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollTableStockReport, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        stockLevelReportPanelLayout.setVerticalGroup(
            stockLevelReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockLevelReportPanelLayout.createSequentialGroup()
                .addGroup(stockLevelReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockLevelReportPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStockTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stockLevelReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMonthPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbYearPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockLevelReportPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(scrollTableStockReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnPrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1445, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(stockLevelReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stockLevelReportPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblStockReportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblStockReportFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStockReportFocusGained

    private void tblStockReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockReportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStockReportMouseClicked

    private void tblStockReportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblStockReportKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStockReportKeyPressed

    private void tblStockReportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblStockReportKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStockReportKeyTyped

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnPrintReport;
    private javax.swing.JComboBox<String> cbMonthPicker;
    private javax.swing.JComboBox<String> cbYearPicker;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblStockTitle;
    private javax.swing.JScrollPane scrollTableStockReport;
    private javax.swing.JPanel stockLevelReportPanel;
    private javax.swing.JTable tblStockReport;
    // End of variables declaration//GEN-END:variables
}
