/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

import Controller.controller;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author amenu
 */
public class stockPanel extends javax.swing.JPanel {

    /**
     * Creates new form stockPanel
     */
    public stockPanel() {
        initComponents();
        fetchAll();
    }
    
        public void fetchAll() {
        tblStock.setModel(DbUtils.resultSetToTableModel(controller.displayStock()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockPanel = new javax.swing.JPanel();
        lblsearchIcon = new javax.swing.JLabel();
        txtSearchStock = new javax.swing.JTextField();
        scrollTableStock = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        lblStockTitle = new javax.swing.JLabel();
        lblPartName = new javax.swing.JLabel();
        txtPartName = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblInitialStock = new javax.swing.JLabel();
        txtInitialStock = new javax.swing.JTextField();
        lblStockUsed = new javax.swing.JLabel();
        txtStockUsed = new javax.swing.JTextField();
        lblNewStockLevel = new javax.swing.JLabel();
        txtNewStockLevel = new javax.swing.JTextField();
        lblThreshold = new javax.swing.JLabel();
        txtThreshold = new javax.swing.JTextField();
        lblDelivery = new javax.swing.JLabel();
        txtDelivery = new javax.swing.JTextField();
        btnUpdatePart = new javax.swing.JButton();
        btnPartOrder = new javax.swing.JButton();
        btnReportPart = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        stockPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblsearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/searchIcon.png"))); // NOI18N

        txtSearchStock.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtSearchStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchStockKeyReleased(evt);
            }
        });

        tblStock.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Part Name", "Quantity", "Stock Level", "Used", "Threshold", "Delivery"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStock.setGridColor(new java.awt.Color(255, 255, 255));
        tblStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblStockFocusGained(evt);
            }
        });
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        tblStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblStockKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblStockKeyTyped(evt);
            }
        });
        scrollTableStock.setViewportView(tblStock);

        lblStockTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblStockTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/stockIcon.png"))); // NOI18N
        lblStockTitle.setText("Stock Detail");

        lblPartName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblPartName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPartName.setText("Part Name:");

        txtPartName.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtPartName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartNameActionPerformed(evt);
            }
        });

        lblQuantity.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantity.setText("Quantity");

        txtQuantity.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblInitialStock.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblInitialStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInitialStock.setText("Initial Stock Level");

        txtInitialStock.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblStockUsed.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblStockUsed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockUsed.setText("Stock Used");

        txtStockUsed.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblNewStockLevel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblNewStockLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewStockLevel.setText("New Stock Level");

        txtNewStockLevel.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblThreshold.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblThreshold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThreshold.setText("Threshold");

        txtThreshold.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        lblDelivery.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblDelivery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelivery.setText("Delivery");

        txtDelivery.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N

        btnUpdatePart.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdatePart.setText("Update Stock ");

        btnPartOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnPartOrder.setText("Part Order");

        btnReportPart.setBackground(new java.awt.Color(255, 255, 255));
        btnReportPart.setText("Report Part");

        javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
        stockPanel.setLayout(stockPanelLayout);
        stockPanelLayout.setHorizontalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(lblsearchIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollTableStock, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addComponent(txtSearchStock))
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(stockPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReportPart, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPartOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(stockPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stockPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnUpdatePart, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stockPanelLayout.createSequentialGroup()
                                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPartName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStockUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInitialStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtThreshold, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNewStockLevel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStockUsed, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInitialStock, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPartName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(stockPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblStockTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        stockPanelLayout.setVerticalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stockPanelLayout.createSequentialGroup()
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblStockTitle)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stockPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblsearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchStock, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(stockPanelLayout.createSequentialGroup()
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPartName)
                            .addComponent(txtPartName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInitialStock)
                            .addComponent(txtInitialStock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStockUsed)
                            .addComponent(txtStockUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewStockLevel)
                            .addComponent(txtNewStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblThreshold)
                            .addComponent(txtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDelivery)
                            .addComponent(txtDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdatePart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPartOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportPart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollTableStock, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblStockFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStockFocusGained

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        // TODO add your handling code here:
        txtPartName.setText(tblStock.getValueAt(tblStock.getSelectedRow(), 0).toString());
        txtQuantity.setText(tblStock.getValueAt(tblStock.getSelectedRow(), 1).toString());
        txtInitialStock.setText(tblStock.getValueAt(tblStock.getSelectedRow(), 2).toString());


        
        txtStockUsed.setText(tblStock.getValueAt(tblStock.getSelectedRow(), 3).toString());
        txtThreshold.setText(tblStock.getValueAt(tblStock.getSelectedRow(), 2).toString());
        txtDelivery.setText(tblStock.getValueAt(tblStock.getSelectedRow(), 3).toString());
        int Stock=Integer.parseInt(txtInitialStock.getText());
        int Used=Integer.parseInt(txtStockUsed.getText());
        int result = Stock - Used;
        txtNewStockLevel.setText(result+"");
    }//GEN-LAST:event_tblStockMouseClicked

    private void tblStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblStockKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStockKeyPressed

    private void tblStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblStockKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblStockKeyTyped

    private void txtPartNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartNameActionPerformed

    private void txtSearchStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchStockKeyReleased
        // TODO add your handling code here:
        
        tblStock.setModel(DbUtils.resultSetToTableModel(controller.searchStock(txtSearchStock.getText())));
    }//GEN-LAST:event_txtSearchStockKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPartOrder;
    private javax.swing.JButton btnReportPart;
    private javax.swing.JButton btnUpdatePart;
    private javax.swing.JLabel lblDelivery;
    private javax.swing.JLabel lblInitialStock;
    private javax.swing.JLabel lblNewStockLevel;
    private javax.swing.JLabel lblPartName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStockTitle;
    private javax.swing.JLabel lblStockUsed;
    private javax.swing.JLabel lblThreshold;
    private javax.swing.JLabel lblsearchIcon;
    private javax.swing.JScrollPane scrollTableStock;
    private javax.swing.JPanel stockPanel;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtDelivery;
    private javax.swing.JTextField txtInitialStock;
    private javax.swing.JTextField txtNewStockLevel;
    private javax.swing.JTextField txtPartName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearchStock;
    private javax.swing.JTextField txtStockUsed;
    private javax.swing.JTextField txtThreshold;
    // End of variables declaration//GEN-END:variables
}
