/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

/**
 *
 * @author amenu
 */
public class vehicleReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form vehicleReportPanel
     */
    public vehicleReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicleReportPanel = new javax.swing.JPanel();
        lblVehicleReport = new javax.swing.JLabel();
        rbMOT = new javax.swing.JRadioButton();
        rbAnnualService = new javax.swing.JRadioButton();
        rbRepair = new javax.swing.JRadioButton();
        rbOverall = new javax.swing.JRadioButton();
        lblDate = new javax.swing.JLabel();
        cbMonthPicker = new javax.swing.JComboBox<>();
        cbYearPicker = new javax.swing.JComboBox<>();
        lblFilter = new javax.swing.JLabel();
        rbCustomerType = new javax.swing.JRadioButton();
        cbCustomerTypePicker = new javax.swing.JComboBox<>();
        btnGenerateReport = new javax.swing.JButton();
        scrollTableVehicle = new javax.swing.JScrollPane();
        tblVehicle = new javax.swing.JTable();
        btnPrintReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        vehicleReportPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblVehicleReport.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblVehicleReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicleReport.setText("Vehicle Report");

        rbMOT.setBackground(new java.awt.Color(255, 255, 255));
        rbMOT.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        rbMOT.setText("MOT");

        rbAnnualService.setBackground(new java.awt.Color(255, 255, 255));
        rbAnnualService.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        rbAnnualService.setText("Annual Service");

        rbRepair.setBackground(new java.awt.Color(255, 255, 255));
        rbRepair.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        rbRepair.setText("Repair");

        rbOverall.setBackground(new java.awt.Color(255, 255, 255));
        rbOverall.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        rbOverall.setText("Overall");

        lblDate.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date");

        cbMonthPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));

        cbYearPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));

        lblFilter.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblFilter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFilter.setText("Filter by");

        rbCustomerType.setBackground(new java.awt.Color(255, 255, 255));
        rbCustomerType.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        rbCustomerType.setText("Customer Type");

        cbCustomerTypePicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Customer Type Here", "Item 2", "Item 3", "Item 4" }));
        cbCustomerTypePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCustomerTypePickerActionPerformed(evt);
            }
        });

        btnGenerateReport.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerateReport.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.setBorder(null);
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        tblVehicle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehicles Booked", "Month", "Job Type", "Customer Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVehicle.setGridColor(new java.awt.Color(255, 255, 255));
        tblVehicle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblVehicleFocusGained(evt);
            }
        });
        tblVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehicleMouseClicked(evt);
            }
        });
        tblVehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblVehicleKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblVehicleKeyTyped(evt);
            }
        });
        scrollTableVehicle.setViewportView(tblVehicle);

        btnPrintReport.setBackground(new java.awt.Color(255, 255, 255));
        btnPrintReport.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnPrintReport.setText("Print Report");
        btnPrintReport.setBorder(null);
        btnPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehicleReportPanelLayout = new javax.swing.GroupLayout(vehicleReportPanel);
        vehicleReportPanel.setLayout(vehicleReportPanelLayout);
        vehicleReportPanelLayout.setHorizontalGroup(
            vehicleReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vehicleReportPanelLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addGroup(vehicleReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicleReport)
                    .addComponent(lblFilter)
                    .addGroup(vehicleReportPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(vehicleReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAnnualService)
                            .addComponent(rbMOT)
                            .addComponent(rbRepair)
                            .addComponent(rbOverall)))
                    .addComponent(lblDate)
                    .addGroup(vehicleReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vehicleReportPanelLayout.createSequentialGroup()
                            .addComponent(cbMonthPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbYearPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rbCustomerType)
                        .addGroup(vehicleReportPanelLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(cbCustomerTypePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnGenerateReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(scrollTableVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        vehicleReportPanelLayout.setVerticalGroup(
            vehicleReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleReportPanelLayout.createSequentialGroup()
                        .addComponent(btnPrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(vehicleReportPanelLayout.createSequentialGroup()
                        .addComponent(lblVehicleReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMOT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbAnnualService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbRepair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOverall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vehicleReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMonthPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbYearPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCustomerType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCustomerTypePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(vehicleReportPanelLayout.createSequentialGroup()
                        .addComponent(scrollTableVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1445, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vehicleReportPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vehicleReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCustomerTypePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCustomerTypePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCustomerTypePickerActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void tblVehicleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblVehicleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVehicleFocusGained

    private void tblVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehicleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVehicleMouseClicked

    private void tblVehicleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblVehicleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVehicleKeyPressed

    private void tblVehicleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblVehicleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVehicleKeyTyped

    private void btnPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnPrintReport;
    private javax.swing.JComboBox<String> cbCustomerTypePicker;
    private javax.swing.JComboBox<String> cbMonthPicker;
    private javax.swing.JComboBox<String> cbYearPicker;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblVehicleReport;
    private javax.swing.JRadioButton rbAnnualService;
    private javax.swing.JRadioButton rbCustomerType;
    private javax.swing.JRadioButton rbMOT;
    private javax.swing.JRadioButton rbOverall;
    private javax.swing.JRadioButton rbRepair;
    private javax.swing.JScrollPane scrollTableVehicle;
    private javax.swing.JTable tblVehicle;
    private javax.swing.JPanel vehicleReportPanel;
    // End of variables declaration//GEN-END:variables
}
